apiVersion: v1
kind: Namespace
metadata:
  name: portainer1

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa
  namespace: portainer1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer1
spec:
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      serviceAccountName: portainer-sa
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer1
spec:
  type: NodePort
  selector:
    app: portainer
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30777
