apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-nfs-pvc
spec:
  storageClassName: portainer-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
