apiVersion: v1
kind: Namespace
metadata:
  name: portainer1

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa
  namespace: portainer1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      serviceAccountName: portainer-sa
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest
        imagePullPolicy: Always
        volumeMounts:
            - name: portainer-data
              mountPath: /data
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: tcp-edge
              containerPort: 8000
              protocol: TCP
      volumes:
        - name: "portainer-data"
          persistentVolumeClaim:
            claimName: portainer-nfs-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer1
spec:
  type: NodePort
  selector:
    app: portainer
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30776
  - name: https
    targetPort: 9443
    protocol: TCP
    port: 9443
    nodePort: 30777
  - name: edge
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30778
