apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-nfs-pv
  namespace: portainer1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: portainer-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/portainer-k8s
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-nfs-pvc
  namespace: portainer1
spec:
  storageClassName: portainer-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
